# Pytorch tutorial - Introduction to Pytorch

## Learn the basics

- https://pytorch.org/tutorials/beginner/basics/intro.html
- we use Fashion MNIST dataset

In [1]:
import numpy as np
import torch
import torch.nn as nn

## Tensors
- https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

```
Tensor vs Ndarray

[공통점]
1. array, matrix를 담는 특화된 자료구조
2. 같은 underlying memory를 공유할 수 있다.

[Tensor만의 특징]
1. GPU 등 다른 하드웨어 가속에서 돌릴 수 있다.
2. 자동 미분의 optimization('Auto Grad')에 특화되어 있다. 

```

### Initializing a Tensor

### tensor's bridge with Numpy
- https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label
```
"Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other. eliminating the need to copy data."
```

#### torch -> numpy

In [4]:
t = torch.ones(5)
n = t.numpy()

print(f"t : {t}")
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [6]:
t.add_(1)

print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


#### numpy -> torch

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

print(f"t : {t}")
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n : [1. 1. 1. 1. 1.]


In [24]:
np.add(n, 1, out=n)

print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]


#### with random or constant values

In [11]:
shape = (2,3)

In [16]:
ones = torch.ones(shape, dtype=torch.float32)
zeros = torch.zeros(shape, dtype=torch.float32)
rands = torch.rand(shape, dtype=torch.float32)

print(ones)
print(zeros)
print(rands)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0812, 0.0089, 0.3017],
        [0.8196, 0.6554, 0.7143]])


### attributes of a tensor
- shape
- dtype
- device

In [19]:
rands.shape

torch.Size([2, 3])

In [20]:
rands.dtype

torch.float32

In [21]:
rands.device

device(type='cpu')

In [23]:
device = 'cuda:0' if torch.cuda.is_available else 'cpu'
device

'cuda:0'

In [28]:
rands = rands.to(device)
rands.device

device(type='cuda', index=0)

### operations on tensors

- https://pytorch.org/docs/stable/torch.html (torch operation code manual)

#### standard numpy-like indexing and slicing

In [32]:
n = np.arange(16).reshape(4,4)
t = torch.from_numpy(n)
t

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [36]:
print(f"first row : {t[0]}")
print(f"first column : {t[:,0]}")
print(f"last column : {t[:, -1]}")
print(f"last column : {t[..., -1]}")

first row : tensor([0, 1, 2, 3])
first column : tensor([ 0,  4,  8, 12])
last column : tensor([ 3,  7, 11, 15])
last column : tensor([ 3,  7, 11, 15])


#### joining tensor

- cat : cat은 존재하는 dimension 하 합치기 (3,3) cat (3,3) -> (6,3)
- stack : 차원을 하나 더한 후 그걸로 합치기 unsqueeze 후 합치는 것과 같다. (3,3) stack (3,3) -> (2,3,3)

#### matrix multiplication / element-wise operation
- tensor.matmul( )
- tensor.mul( )

In [38]:
t = torch.from_numpy(np.arange(16).reshape(4,4))
t_mat = t.matmul(t.T)

In [41]:
t

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [42]:
t.T

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

In [39]:
t_mat

tensor([[ 14,  38,  62,  86],
        [ 38, 126, 214, 302],
        [ 62, 214, 366, 518],
        [ 86, 302, 518, 734]])

In [40]:
t_ele = t.mul(t.T)
t_ele

tensor([[  0,   4,  16,  36],
        [  4,  25,  54,  91],
        [ 16,  54, 100, 154],
        [ 36,  91, 154, 225]])